name: SourceTracker CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: sourcetracker3
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          python-version: ${{ matrix.python-version }}

      - name: Install conda packages
        shell: bash -l {0}
        run: mamba install -c conda-forge cmdstanpy pandas biom-format numpy flake8 pytest joblib

      - name: Install SourceTracker3
        shell: bash -l {0}
        run: pip install -e .

      - name: Check style
        shell: bash -l {0}
        run: make stylecheck

      - name: Run tests
        shell: bash -l {0}
        run: make test
